export const options: string[] = [
  'Grocery',
  'Clothing',
  'Electronics',
  'Bookstore',
  'Pharmacy',
  'Furniture',
  'Sports',
  'Jewelry',
  'Beauty',
  'Home Improvement',
  'Pet Supplies',
  'Toys',
  'Automotive',
  'Other',
  'Office Supplies',
  'Garden',
  'Music',
  'Movies',
  'Video Games',
  'Health & Wellness',
  'Baby Products',
  'Crafts',
  'Outdoor Equipment',
  'Tools',
  'Bags & Accessories',
  'Footwear',
  'Bedding',
  'Kitchenware',
  'Stationery',
  'Groceries & Food',
  'Cleaning Supplies',
  'Party Supplies',
  'Travel',
  'Watches',
  'Eyewear',
  'Art Supplies',
  'Fitness Equipment',
  'Building Materials',
  'Lighting',
  'Electrical',
  'Plumbing',
  'Heating & Cooling',
  'Seasonal Decor',
  'Cameras & Photography',
  'Computers & Accessories',
  'Phones & Accessories',
  'Smart Home Devices',
  'Musical Instruments',
  'Books & Magazines',
  'Board Games',
  'Luggage',
  'Hiking & Camping Gear',
  'Marine & Water Sports',
  'Fishing Equipment',
  'Cycling Gear',
  'Skateboarding',
  'Winter Sports',
  'Yoga & Pilates',
  'Personal Care',
  'Wine & Spirits',
  'Office Furniture',
  'Safety & Security',
  'Industrial Equipment',
  'Educational Supplies',
  'Gift Cards',
];
